### ISSUE TITLE
Mengenfehler

### ISSUE THREAD

**Issue by ScyllaHide** [henrydatei/TUD_MATH_BA#13]
**Fehlerbeschreibung**
Teilmenge → größergleich

**Ort des Fehlers**

- Semester: 2
- Vorlesung: LAAG
- Kapitel: Dualität
- Abschnitt: Ordnungsrelationen
- Nummer: Bsp 1.4.4

**Comment by henrydatei** [comment]
Der Abschnitt ist nicht "Ordnungsrelationen", sondern "Das Lemma von Zorn"!

**Comment by henrydatei** [comment]
done
