### ISSUE TITLE
Anführungszeichen Fehler

### ISSUE THREAD

**Issue by RobWalt** [henrydatei/TUD_MATH_BA#20]
**Fehlerbeschreibung**

Die Anführungszeichen führen zu Fehlern in der PDF.

Nutze z.B. ```\dq TEXT\dq{}``` anstatt ```"TEXT"```

**Ort des Fehlers**
- Semester: 1
- Vorlesung: ANAG
- Kapitel: 1
- Abschnitt: ganz am Anfang schon, Definition von Aussage
- Nummer:
- alternativ Seite des Skripts:

**Comment by henrydatei** [comment]
Ja, das war der Anfang von ANAG 1, den wir mittlerweile aufgegeben haben zu schreiben (ich weiß gar nicht, warum der überhaupt noch online ist...). Ansonsten haben wir im 2. Semester ein Skript, das ANAG 1 und 2 zusammen enthält und deutlich besser ist (https://github.com/henrydatei/TUD_MATH_BA/blob/master/2.%20Semester/ANAG%201%2B2%20Semester/Vorlesung%20ANAG.pdf)
