### ISSUE TITLE
Rechtliches

### ISSUE THREAD

**Issue by vale981** [henrydatei/TUD_MATH_BA#38]
Prof. Schuricht erklaerte uns heute, dass er gegen die Veroeffentlichung der Inhalte seiner Vorlesung unter Umstaenden rechtlich vorgeht!

Wir sollten also die Tafel-Bilder sowie die (ANAG) Repository privat machen + das Zeug fuer uns (die Studenten) behalten...

**Comment by vale981** [comment]
Ich bin idiotisch genug gewesen bei der anfolgenden Diskussion, fragen bezueglich der Skripte zu stellen... 
Desswegen der Aufruhr.

Ich entschuldige mich und hoffe, dass ich meine Gusche in Zukunft halte.

**Comment by henrydatei** [comment]
Den Link zu den Fotos können wir wegmachen, allerdings würde ich erst das Repository auf "Private" stellen, wenn ich tatsächlich eine Takedown-Notice bekomme. @ScyllaHide meinte, dass man diese einige Stunden vor der Löschung des Repos bekommen würde. Gleichzeitig wollen wir noch ein paar Accounts machen, die das Repo forken. Wenn Schuricht die Forks nicht mit angibt, werden diese auch nicht gelöscht.

**Comment by henrydatei** [comment]
Allerdings bezweifle ich, dass Schuricht so technikaffig ist, dass er dieses Repo schließen kann. Github nimmt die Repos nur herunter, wenn große Firmen Takedown-Notices stellen, aber nicht, wenn irgendein Prof aus Deutschland da meint, sein Urheberrecht sei verletzt.

**Comment by henrydatei** [comment]
Ansonsten bin ich schon dabei alle Informationen von meinen Profil zu entfernen, die Rückschlüsse auf meine Identität zulassen. Ich empfehle das dies alle tun (@vale981 @epsilonbelowzero @ScyllaHide @Palindrom73 ).

Ich muss dann noch durch die Dateien durch und dort alle Namen entfernen, also insbesondere in den Vorworten.

**Comment by vale981** [comment]
Aber eine Private repo waehre eig. kein Problem.
Konfrontation mit Prof. Schuricht ist doch nicht sinnvoll.

**Comment by vale981** [comment]
evtl auf http://git.protagon.space:3000/

**Comment by vale981** [comment]
Einverstaendniss einhohlen?

**Comment by henrydatei** [comment]
Ich hab die problematischen Dateien auf https://github.com/henrydatei/TUD_MATH_Schuricht verschoben

**Comment by henrydatei** [comment]
@vale981 wie hat er unser Repo eigentlich gefunden? Kannst du ihn das mal fragen?

**Comment by vale981** [comment]
Keen plan. Ich habs ihm ned verraten...
Evtl hat er was anderes gefunden?

**Comment by henrydatei** [comment]
Invite-Links https://github.com/henrydatei/TUD_MATH_Schuricht/invitations
