### ISSUE TITLE
Falscher Term

### ISSUE THREAD

**Issue by epsilonbelowzero** [henrydatei/TUD_MATH_BA#46]
**Fehlerbeschreibung**
Der Nenner bei K_{12} (nach 1. =) ist quatsch. Der Nenner müsste \frac q{-p+\sqrt{p^2-q} sein.

**Ort des Fehlers**
- Semester: 3
- Vorlesung: Nume
- Kapitel: 4
- Abschnitt: 2
- Nummer: Bsp. 2.5
- alternativ Seite des Skripts:

**Comment by henrydatei** [comment]
Aber steht das nicht genau so im Skript?
![image](https://user-images.githubusercontent.com/31316025/52671799-fd2d4f80-2f13-11e9-872a-0b16287c6a68.png)

**Comment by epsilonbelowzero** [comment]
Ne. Wie du von dem ersten Betrag zum Zweiten kommst, ist mir nicht ganz klar. Der Nenner des ersten Faktors in der ersten Gleichheit mit Betrag müsste wie oben sein, also ein Doppelbruch.

**Comment by henrydatei** [comment]
Hä, ich verstehe einfach nicht, was du willst.
Fischers Skript:
![image](https://user-images.githubusercontent.com/31316025/52744745-6c1ead00-2fd5-11e9-8f23-ef800deee54a.png)

Mein Skript:
![image](https://user-images.githubusercontent.com/31316025/52744676-42fe1c80-2fd5-11e9-8d46-6f63d7b1b59c.png)

**Comment by henrydatei** [comment]
soweit wie ich feststelle, sind da keine Unterschiede drin

**Comment by henrydatei** [comment]
falscher knopf...

**Comment by epsilonbelowzero** [comment]
Dann ist in seinem Skript auch der Fehler drin. Die Konditionszahl für eine Aufgabe ist definiert durch K_{ij} = \Vert \frac{a_j}{\Phi_i(a)} \frac{\partial \Phi(a)}{a_j}\Vert. Da \Phi(q,p) = \frac q{-p-\sqrt{p^2-q}}, ist dann der erste Faktor
\dfrac q{\frac q{-p-\sqrt{p^2-q}}} \cdot <Ableitungskram>,
also ein Doppelbruch. Die Umformung vom ersten Betrag zum zweiten Betrag würde mich sonst mal sehr interessieren, auf, wie man auf diesen ersten Betragsterm kommt, der doch anders als die Definition ist.

**Comment by henrydatei** [comment]
kannst du das in den Dateien fixen?

**Comment by epsilonbelowzero** [comment]
Jo

**Comment by ScyllaHide** [comment]
ist es gefixt? weil dann könnten wir das closen.

**Comment by henrydatei** [comment]
nein, @epsilonbelowzero wollte das fixen, hat es aber bis jetzt noch nicht

**Comment by henrydatei** [comment]
Dieser Issue ist nun seit mehr als einem Jahr offen .... @epsilonbelowzero wolltest du das nicht fixen?
