### ISSUE TITLE
Falsche Startbedingung

### ISSUE THREAD

**Issue by Palindrom73** [henrydatei/TUD_MATH_BA#47]
Im letzten Teil des Algorithmus, also in der letzten FOR Schleife, müsste es nicht dort von j=k anfangen zu laufen anstatt von j=k+1, sonst würde ja quasi, in dem Fall für k=1 z.B. a_{21} nicht ausgelöscht werden und das ganze würde sich induktiv fortpflanzen.

**Ort des Fehlers**
3. Semester
NUME
Kapitel III
Abschnitt 1.1
Algorithmus 1.2

**Comment by henrydatei** [comment]
Das Problem bei Fischers "Algorithmen" ist, dass eigentlich keiner davon lauffähig ist. Wir hatten diese Diskussion doch in der ersten Vorlesung und sind zu dem Schluss gekommen, dass die Algorithmen dann viel komplexer werden würden, wenn die wirklich lauffähig und ready-to-implement sein sollten. Ich glaube es geht bei diesen Algorithmen nur darum, dass man sieht wie groß die Komplexität ist.

**Comment by henrydatei** [comment]
Vielleicht sollte man die Algorithmen mal auf einem PC laufen lassen und schauen, ob sie funktionieren...
