### ISSUE TITLE
Falsche Ableitung

### ISSUE THREAD

**Issue by epsilonbelowzero** [henrydatei/TUD_MATH_BA#48]
**Fehlerbeschreibung**
In Formel (3) sollte die erste, nicht die zweite Ableitung, beschränkt sein (zweite wäre sinnlos und ist ggf nicht mal existent)

**Ort des Fehlers**
- Semester: 3
- Vorlesung: NUME
- Kapitel: 5
- Abschnitt: 1
- Nummer: Beweis Satz 1.3
- alternativ Seite des Skripts:

**Comment by henrydatei** [comment]
Bereitest dich wohl auf NUME vor?

**Comment by epsilonbelowzero** [comment]
Wie kommst du darauf? :D

**Comment by henrydatei** [comment]
ja, das ist tatsächlich die erste Ableitung, nicht die zweite. Fixe ich später
