### ISSUE TITLE
Stochastik-Skript an Vorlesung angleichen

### ISSUE THREAD

**Issue by SaschaFroelich** [henrydatei/TUD_MATH_BA#54]
Hallo,

wäre es evtl. möglich, die Nummerierungen der Kapitel/Definitionen/Beispiele/Lemmas etc. im Stochastik-Skript (4. Semester) an die Nummerierung anzugleichen, welche in der Vorlesung verwendet werden? Das würde den Vergleich von eigenhändigen Mitschriften mit dem Skript sehr vereinfachen.

Ich würde mich dazu auch bereit erklären, falls Bedarf besteht.

Grüße
Sascha

**Comment by henrydatei** [comment]
Da ich gerade ein Erasmus-Semester mache, dann ich nicht sagen, wie die Nummerierung in der Vorlesung ist. Wir haben die Definitionen/Beispiele/Lemmas/... so nummeriert, wie es Prof. Fehm in LAAG1 gemacht hat und dieses Template für alle weiteren Vorlesungen benutzt. Insbesondere in NUME und NUMM hat sich dadurch die Nummerierung deutlich verschoben. Aktuell habe ich keine Ambitionen, für diese Vorlesungen die Nummerierung anzupassen, aber vielleicht hat @epsilonbelowzero da Lust für eine neue Option und die Nummerierung zu ändern 😄

**Comment by ScyllaHide** [comment]
Ja die Nummerierung muss noch repariert werden, im Moment habe ich dazu echt keine Zeit. Ich überlege dazu eine lokale enviroments datei anzulegen, da sich im Moment alles, glaub ich auf der Satzumgebung bezieht.

@SaschaFroelich Es würde helfen, wenn du vielleicht mir sagen könntest, ob Lemmas, Sätze usw durchgezählt werden und wenn nein, ob das sich nach Kapiteln oder nach was sich das richtet? (glaube im Moment nach sections)

Gibt ja auch VL die Theoreme einzeln Benummern und den Rest einfach durchnummerieren ... Muss ich da auch noch fixen 👎

**Comment by SaschaFroelich** [comment]
@ScyllaHide Es ist relativ simpel, es geht natürlich nach Kapiteln (1 Grundbegriffe der Wtheorie, 2 Erste Standardmodelle der WTheorie, 3 Bedingte Wkeiten und (Un-)abhängigkeit etc.). Innerhalb der Kapitel wird dann einfach alles durchnummeriert ohne Unterschiede nach Sektionen im Kapitel oder nach Satz, Bsp, Lemma usw. zu machen. Also z.B.

**Kapitel 3: Beingte Wkeiten und (Un-)abhängigkeit**
**3.1: Bedingte Wkeiten**

Bsp. 3.1: ...
Lemma 3.2: ...
Def. 3.3: ...
Bsp. 3.4: ...
Lemma 3.5: ...
usw.
Bsp. 3.10: ...

**3.2 Unabhängigkeit**
Def. 3.11:
Bsp. 3.12:


Cheers!

**Comment by ScyllaHide** [comment]
@SaschaFroelich Ich werd mal schaun, ob ich das irgendwie schnell fixen kann.  Ansonsten muss @epsilonbelowzero sich das, wenn er Zeit hat, mal anschaun.

Also Faltung wird im neuen commit als **Definition III.24**, zum Not geht as erstmal.

**Comment by henrydatei** [comment]
soweit ich das sehe hat @ScyllaHide das mit der Nummerierung gefixt, auch wenn etwas unsauber. Ich schließe deswegen mal den Issue.
