### ISSUE TITLE
Update STOCH-Skript

### ISSUE THREAD

**Issue by SaschaFroelich** [henrydatei/TUD_MATH_BA#55]
Hallo Freunde,

wird an dem Stochastik-Skript noch weitergeschrieben? Ich bin darauf eigentlich angewiesen, weil ich nicht immer in die VL gehen kann. Wenn das aber nicht weitergeführt wird kann ich mir auch anderweitig helfen. Würde es nur gerne wissen.

Ich habe auch versucht mir das Repo runterzuladen und das PDF selbst zu erstellen, ich kriege dabei allerdings einen Haufen Fehlermeldungen und Formatierungsprobleme.

LG

**Comment by henrydatei** [comment]
Also eigentlich sollte an dem Skript noch weitergeschrieben werden. Ich bin aber selber gerade im Ausland, kann da also nicht wirklich viel zu sagen. 

Wegen den Fehlermeldungen: Du brauchst eine komplette Latex-Installation (etwa 8GB). Als Distribution verwende ich TeXLive, es müssten allerdings auch andere Distros gehen. Mach am besten dazu noch mal einen neuen Issue auf und kopiere da die Fehlermeldungen rein

**Comment by henrydatei** [comment]
Ich hab gerade noch mal was gepusht, weiß aber nicht, ob das der aktuelle Stand der VL ist.

Ansonsten sind das hier die Mitschriften von jemanden:
![1](https://user-images.githubusercontent.com/31316025/57297699-41219200-70c8-11e9-871b-0fa13b57f4b2.jpeg)
![2](https://user-images.githubusercontent.com/31316025/57297701-41219200-70c8-11e9-8409-2834fe99aabf.jpeg)
![3](https://user-images.githubusercontent.com/31316025/57297703-41ba2880-70c8-11e9-9e1a-f60ef113e57c.jpeg)
![4](https://user-images.githubusercontent.com/31316025/57297705-41ba2880-70c8-11e9-9f04-fe802fcf9e45.jpeg)
![5](https://user-images.githubusercontent.com/31316025/57297706-41ba2880-70c8-11e9-9199-815d002b16a5.jpeg)

**Comment by SaschaFroelich** [comment]
Also zunächste danke für die Mitschrift. Außerdem wurde das Skript nun aktualisiert, auch danke dafür. 

Ich habe meine Distro aktualisiert und die fehlenden Packages installiert, und bekomme nun keine Fehlermeldung mehr. Daher schließe ich die Issue.
