### ISSUE TITLE
Fehler in Referenzen

### ISSUE THREAD

**Issue by SaschaFroelich** [henrydatei/TUD_MATH_BA#56]
Hallo,

ich bins mal wieder! 

Danke für's Anpassen der Referenzen. Allerdings: Kapitel IV fängt sofort mit Definition IV.2 an (negative Binomialverteilung, geometrische Verteilung). Dabei müsste das Definition IV.1 sein.

LG
Sascha

**Comment by ScyllaHide** [comment]
ja weis ich, ich habe keine Zeit mir das anzuschauen im Moment, wird vermutlich erst am WE werden, da die Woche echt richtig voll ist.

**Comment by henrydatei** [comment]
also die Referenzen habe ich schon gefixt, da musst du nix mehr machen

**Comment by henrydatei** [comment]
@SaschaFroelich ich habe dich mal als Collaborator hinzugefügt, da kannst du die Rechtschreibfehler selber beheben

**Comment by SaschaFroelich** [comment]
Ok danke
