### ISSUE TITLE
Fehler im STOCH-Skript?

### ISSUE THREAD

**Issue by SaschaFroelich** [henrydatei/TUD_MATH_BA#61]
**Fehlerbeschreibung**
In der Definition für Zufallsvariablen steht eine ZV $X:\Omega \rightarrow \Omega'$ sei eine ZV *auf* $(\Omega',\mathcal{F}')$, während Wikipedia sagt, es sei dann eine ZV auf $(\Omega,\mathcal{F})$. Welches ist nun richtig? Ich habe die Mitschrift aus der Stunde nicht, kann vielleicht jemand nochmal nachschauen?

**Ort des Fehlers**
- Semester: 4
- Vorlesung: Stochastik
- Definition I.12

**Comment by henrydatei** [comment]
hab die Mitschrift auch nicht, @ScyllaHide wie sieht es bei dir aus?

**Comment by SaschaFroelich** [comment]
Hab nochmal nachgefragt. Im Skript war's falsch, hab's korrigiert.

LG

**Comment by ScyllaHide** [comment]
> 
> 
> hab die Mitschrift auch nicht, @ScyllaHide wie sieht es bei dir aus?

die PDF ist meine Mitschrift.
