### ISSUE TITLE
LostInDarkMath meint, dass wir seinen Tex-Code benutzen, ohne den Urheber anzugeben

### ISSUE THREAD

**Issue by henrydatei** [henrydatei/TUD_MATH_BA#66]
insbesondere @epsilonbelowzero, kannst du da mal gucken, inwiefern wir so was machen? Also in den Config-Dateiein und so.

**Comment by henrydatei** [comment]
https://github.com/ScyllaHide/Exercises_SS19/issues/1

**Comment by LostInDarkMath** [comment]
Ich beziehe mich vor allem auf die folgenden Commit:
https://github.com/henrydatei/TUD_MATH_BA/commit/701e4ed2a7033ab06b09d69544ad8b7ec01fe8ef#diff-afa1fa3db7912b906cc543e36c680d0e

**Comment by henrydatei** [comment]
Also den Code hab ich nicht geschrieben, dass müsste von @Ameyah sein. Aber wenn ich die Kommentare im Code richtig deute, kommt das von Stackoverflow und nicht von dir

**Comment by LostInDarkMath** [comment]
Ja, der Commit ist von Pascal. Den Kommentar habe ich geschrieben, um dem Urheber des Codes entsprechend anzugeben (sonst wärs es ja Doppelmoral). Den Code habe ich allerdings modifiziert und angepasst. Konkret gesprochen habe ich die binäre Variante ergänzt für bspw. Skalarprodukte.

**Comment by henrydatei** [comment]
ok, ich schreib dich als Urheber mit rein

**Comment by LostInDarkMath** [comment]
Thx. Geht mir auch gar nicht darum, hier irgendwas einzuschränken. Ich bin für freie Software und für Wiederverwendbarkeit. Wollte das nur noch mal klarstellen.

Und allgemein war es eher Pascals Repo https://github.com/ScyllaHide was mich dann wirklich gestört hat. Einfach alles kopieren ohne Erwähnung... Ich finde, da ist dann auch eine Grenze überschritten.

Aber wie gesagt, im Grunde bin ich froh, wenn mein Code wiederverwendet wird. Nur das kein falsches Bild entsteht ;)

**Comment by ScyllaHide** [comment]
@LostInDarkMath Sorry da habe ich nicht daran gedacht, eigentlich wollte ich das repo auch private lassen. Also ich hoffe jetzt ist alles geklärt und alles OK.
