### ISSUE TITLE
Riot KaTeX

### ISSUE THREAD

**Issue by vale981** [henrydatei/TUD_MATH_BA#67]
Da ich keine Email von dir habe, mach ich mal in den Issues Werbung: https://addons.mozilla.org/en-US/firefox/addon/riot-katex/

Falls ihr auch Vorlesung ueber Matrix habt, ist das praktisch fuer euch :)

**Comment by henrydatei** [comment]
Was ist ein Riot Chat?

Von meinem iPhone gesendet

**Comment by vale981** [comment]
matrix.tu-dresden.de
viele Vorlesungen nutzen dass
