### ISSUE TITLE
Für die Vorlesungensmatrialien

### ISSUE THREAD

**Issue by baobao-sihan** [henrydatei/TUD_MATH_BA#69]
**E-Mail-Adresse** (nur TU-Mail akzeptiert):
Meine E-Mail ist ：sihan.liu@mailbox.tu-dresden.de, ich bin ein internationaler Studentin, die Sprache ist nicht gut, sehr brauchen das erste Semester und das zweite Semester des vorlesungsmaterialien, danke für Ihre Hilfe!!

**Comment by henrydatei** [comment]
hab ich gesendet
